# -*- coding: utf-8 -*-
"""Laplacian_mat_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SA2GvSOXTe4fv-NBhLYRxyCpKqLx7n3H
"""

import numpy as np
from sklearn.datasets import make_moons
import matplotlib.pyplot as plt
from sklearn.metrics import pairwise_distances
from scipy.io import savemat

X, y = make_moons(n_samples=1000, noise=.05)
#plt.scatter(X.T[0], X.T[1], c=y);
sigma = 0.025;
from sklearn.metrics import pairwise_distances
A = np.exp(- 1./(2 * sigma) * pairwise_distances(X, metric='sqeuclidean'))
# choice of sigma is important above
D = sum(np.diag(A))
L = np.power(D, -0.5) * A * np.power(D, -0.5)
print(L)
# Define the filename for the MATLAB '.mat' file
mat_file_name = 'laplacian_matrix.mat'

# Convert the Laplacian matrix 'L' to a dictionary
mat_dict = {'L': L}

# Save the dictionary as a MATLAB '.mat' file
savemat(mat_file_name, mat_dict)